// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiWCA6Nn9SqIaGw_dWj_IT4Jnkv3bUppA',
    appId: '1:1091563745422:android:0d62d261b872a9d5dd59df',
    messagingSenderId: '1091563745422',
    projectId: 'entrepreneur-plus',
    storageBucket: 'entrepreneur-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KXwAg_qxL_sYMNO1hQFiB_eb5b3Jhv4',
    appId: '1:1091563745422:ios:9d8ba9ad17dc3f19dd59df',
    messagingSenderId: '1091563745422',
    projectId: 'entrepreneur-plus',
    storageBucket: 'entrepreneur-plus.firebasestorage.app',
    iosBundleId: 'com.example.entrepreneurPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoe7ob50PuwShWOdFtfwMpfQeGLafgsys',
    appId: '1:1091563745422:web:9b6afef01bc6bde5dd59df',
    messagingSenderId: '1091563745422',
    projectId: 'entrepreneur-plus',
    authDomain: 'entrepreneur-plus.firebaseapp.com',
    storageBucket: 'entrepreneur-plus.firebasestorage.app',
  );
}
